name: Python

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GBIF_USER: ${{ secrets.GBIF_USER }}
      GBIF_PWD: ${{ secrets.GBIF_PWD }}
      GBIF_EMAIL: ${{ secrets.GBIF_EMAIL }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgeos-dev libgeos-c1v5 libgeos-3.8.2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Install pygbif
      run: make
    - name: Tests
      run: pytest
    - name: Test coverage
      if: matrix.python-version == '3.9'
      run: |
        python3 -m "pytest" --cov-report=xml --cov=pygbif test/
        codecov
